### ISSUE TITLE
"Headers is not defined" when using storyblokApi.get()

### ISSUE THREAD

**Issue by SebbeJohansson** [storyblok/storyblok-vue#251]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

"Headers is not defined" is thrown when using storyblokApi.get()
---
![image](https://user-images.githubusercontent.com/5083273/229592920-adc35ede-dc6a-4c46-a7db-776d99793c8a.png)

## Expected Behavior

I expect the function to run just fine.

## Current Behavior

It errors.

## Steps to Reproduce

1. Clone https://github.com/SebbeJohansson/storyblok-nuxt-ultimate-template/tree/feature/proper-prerendering
2. Open terminal.
3. Run `yarn deploy`

**Comment by Dawntraoz** [comment]
Closing the issue since this was tackled in the JS SDK with the FAQ of the workaround -> https://www.storyblok.com/faq/headers-not-defined-storyblok-sdk
