### ISSUE TITLE
textRendered change the background color instead of the text color

### ISSUE THREAD

**Issue by iruldi** [storyblok/storyblok-vue#253]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

textRendered change the background color instead of the text color
---

## Expected Behavior

textRendered should change the text color

## Current Behavior

textRendered change the background color

![alt text](https://media.discordapp.net/attachments/700345807861317662/1093513367710355516/Screenshot_2023-04-06_at_21.30.26.png?width=299&height=468)

![](https://media.discordapp.net/attachments/700345807861317662/1093513505325449247/Screenshot_2023-04-06_at_21.30.38.png?width=368&height=192)

![](https://media.discordapp.net/attachments/700345807861317662/1093513603056947262/Screenshot_2023-04-06_at_21.31.10.png?width=866&height=94)

## Steps to Reproduce

1. Make a blok with rich text field
2. Fill the field and change the color of the text
3. Check if the color of the text changed

**Comment by elvismercado** [comment]
I don't know if you are describing your issue correctly.
But i think i have a similar issue.

I followed the docs as they are on this page: https://github.com/storyblok/storyblok-vue#rendering-rich-text
In the richtext field i add a color to a part of the text but after passing the storyblok content through the renderRichtext method the value is not as expected.
See screenshots:

![Screenshot from 2023-04-14 12-43-16](https://user-images.githubusercontent.com/3658208/232023688-a65df940-4c53-48a5-a493-3250c50b2381.png)

![Screenshot from 2023-04-14 12-39-55](https://user-images.githubusercontent.com/3658208/232023505-5edfef87-6e54-4077-929f-e43a18afd409.png)

![Screenshot from 2023-04-14 12-37-14](https://user-images.githubusercontent.com/3658208/232023533-a89c7585-d564-416d-9358-c82fb8f3dbeb.png)

**Comment by stijn-ways** [comment]
Same issue here.

```vue
<script setup>
const props = defineProps({ html: Object });
const html = computed(() =>
  renderRichText(props.html).replaceAll("<p> </p>", "")
);
</script>

<template>
  <div v-html="html"></div>
</template>
```

![image](https://user-images.githubusercontent.com/127141824/235306383-ef2cc712-431d-4ed7-8d3d-28cdbaadeff4.png)

**Comment by alvarosabu** [comment]
Hi there @iruldi thanks for reporting the issue. Indeed several users reported this and it was fixed on https://github.com/storyblok/storyblok-js-client/pull/520 on the https://github.com/storyblok/storyblok-js-client repo.

We're currently waiting to update the versions on the SDKs to have this fixed as soon as possible. I will update this ticket when is done.

Thanks
