### ISSUE TITLE
Attributes added from Storyblok Bridge in Production

### ISSUE THREAD

**Issue by mrillusion** [storyblok/storyblok-vue#404]
### Describe the issue you're facing

The Storyblok module for Nuxt is adding `data-blok-c="undefined"`, `data-blok-uid="undefined"` & `class="storyblok__outline"` to my production/published website.

Note - runtimeConfig.public.currentEnv = published
```
const story = await useAsyncStoryblok(
  route && route.path !== "/" ? route.path : "home",
  {
    version: runtimeConfig.public.currentEnv,
    resolve_relations: resolveRelations,
  }
);
```

And my nuxt.config.ts module config for Storyblok is as follows,
```
[
  "@storyblok/nuxt",
  {
    accessToken: process.env.STORYBLOK_TOKEN,
    bridge: process.env.ENV !== "published",
  },
],
```

I understand they are from the Storyblok bridge in staging/draft but there doesn't seem to be a way to disable it for prod?

### Reproduction

https://stackblitz.com/edit/nuxt-3-quickstart-demo-tqrrnw?file=nuxt.config.js

### Steps to reproduce

View attributes added in HTML elements

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 532.08 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
    pnpm: 8.6.10 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 115.0.5790.170
    Chrome Canary: 113.0.5660.0
    Safari: 16.6
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by Dawntraoz** [comment]
Hi @manniL can you check if, after the changes, you will still need to stub the functionality? Or it's already tackling all the use cases you have? https://github.com/storyblok/storyblok-vue/pull/405/files

**Comment by manniL** [comment]
Hey @Dawntraoz - that should resolve my issues with it at least 😋
