### ISSUE TITLE
Errors with useStoryblokApi().flushCache()

### ISSUE THREAD

**Issue by codeflorist** [storyblok/storyblok-vue#573]
### Describe the issue you're facing

I want to include a button to flush the storyblok cache in my app.

`storyblok-js-client` provides the [`flushCache`](https://github.com/storyblok/storyblok-js-client/?tab=readme-ov-file#method-storyblokflushcache) method. This method is also exported by `useStoryblokApi()`, but does not seem to work.

This is what i tried:
```vue
<template>
  <div id="app">
    <button @click="flushCache()">Flush Cache</button>
  </div>
</template>

<script setup>
import { useStoryblokApi } from '@storyblok/vue';
const { flushCache } = useStoryblokApi();
</script>
```

This however leads to errors in the console.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-kkwgr2?file=src%2FApp.vue

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.14.0 - /usr/local/bin/pnpm
```

### Used Package Manager

npm

### Error logs (Optional)

```
[Vue warn]: Unhandled error during execution of native event handler at <App>

Uncaught (in promise) TypeError: this.cacheProvider is not a function
    at Proxy.flushCache (@storyblok_vue.js?v=0827989e:855:23)
    at _createElementVNode.onClick._cache.<computed>._cache.<computed> (App.vue:3:21)
    at callWithErrorHandling (chunk-PD2AWGJV.js?v=c8f9ff0a:1652:19)
    at callWithAsyncErrorHandling (chunk-PD2AWGJV.js?v=c8f9ff0a:1659:17)
    at HTMLButtonElement.invoker (chunk-PD2AWGJV.js?v=c8f9ff0a:10271:5)
```

### Validations

- [X] Follow our [Code of Conduct](https://www.storyblok.com/trust-center#code-of-conduct?utm_source=github.com&utm_medium=readme&utm_campaign=storyblok-js-client)

**Comment by Dawntraoz** [comment]
Hi @codeflorist, after checking your reproduction in Stackblitz (btw thank you for always taking the time to make a proper reproduction, this makes it so easy for us 😍), I saw the issue: it seems that when destructuring the method it's losing the context, so if you do this, should work 👇🏼

```vue
<template>
  <div id="app">
    <button @click="flushCache()">Flush Cache</button>
  </div>
</template>

<script setup>
import { useStoryblokApi } from '@storyblok/vue';
const flushCache = () => useStoryblokApi().flushCache();
</script>
```

**Comment by codeflorist** [comment]
Hey @Dawntraoz,

It's working. Many thanks again for your always impeccable support! 👍 I'm glad if i can be of help!
